version: '3.1'
services:
  fast-data-dev:
    image: landoop/fast-data-dev:latest
    container_name: fast-data-dev
    environment:
      RUNTESTS: 0
      SAMPLEDATA: 0
      ADV_HOST: "127.0.0.1" # Advertised host so Kafka is accessible at localhost:9092
    ports:
      - "2181:2181"  # Zookeeper
      - "3030:3030"  # Landoop Web UI
      - "8081:8081"  # Schema Registry (if needed)
      - "8082:8082"  # REST Proxy (if included)
      - "8083:8083"  # Kafka Connect (if included)
      - "9092:9092"  # Kafka Broker
    # Optionally, you can define volumes or additional configurations here.
