spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topic: quickstart # The existing topic for consuming messages
  exchanges:
    topic: processed-exchanges # The topic for processed exchanges
  gpt:
    topic: gpt-rated-exchanges # The new topic for ChatGPT-rated exchanges
